// Generated by https://quicktype.io

export interface ProductID {
  message: string;
  messageType: string;
  totales: Totales;
  data: ProductDetail;
}

export interface ProductDetail {
  idp: number;
  id_o: number;
  id_category: string;
  proname: string;
  file_name: string;
  add_data: string;
  categories: string;
  cat_name: string;
  availability: string;
  unlimited_availability: number;
  code: string;
  options: string;
  description: string;
  images: string;
  url_image: string;
  attribute_offer: string;
  attribute_price: string;
  tax: string;
  price: string;
  pl_multitax: string;
  minimun: string;
  attribute_name: number;
  attr_title: string;
  by_exposure: number;
  offer: string;
  activo: number;
  marked: number;
  filter_body: number;
  active: number;
  as_filter: number;
  visible: number;
  img: Img[];
  opcAdicional: any[];
  opcMedidas: any[];
  atributos: Atributo[];
  tags: Tag[];
  related: Related[];
}

export interface Atributo {
  id_o: number;
  attr_title: string;
  attribute_price: string;
  id_attr_name: number;
}

export interface Img {
  id: number;
  id_category: number;
  id_product: number;
  id_attribute: number;
  id_option: number;
  sku: number;
  ean: number;
  img_path: string;
  img_name: string;
  img_order: number;
  img_order_web: number;
  created: string;
  modified: string;
  status: number;
  laravel_through_key: number;
}

export interface Related {
  id: number;
  name: string;
  file_name: string;
  simulator_name: string;
  tag_extra: string;
  tag_extra_name: string;
  images: string;
  url_image: string;
  description: string;
  categories: string;
  suppliers: number;
  code: string;
  price: string;
  offer: string;
  tax: string;
  price_with_tax: number;
  availability: string;
  unlimited_availability: number;
  units: string;
  attributes: string;
  comments: string;
  options: string;
  tags: string;
  add_data: string;
  by_exposure: number;
  meta_title: string;
  meta_keywords: string;
  meta_description: string;
  price_catalog: string;
  marked: number;
  visible: number;
  active: number;
  showcase: number;
  pl_multitax: string;
  porte: string;
  id_product: number;
  id_related_product: number;
  minimo: string;
  offert: string;
  ida: number;
}

export interface Tag {
  id: number;
  id_product: number;
  id_attribute_value: number;
  url_tag: string;
  desc_tag: string;
  title_tag: string;
  value_tag: string;
  print_tag: number;
  print_pral: number;
}

export interface Totales {
  attrs: number;
  tags: number;
  image: number;
  opcAdicional: number;
  opcMedidas: number;
  related: number;
}

// interfaces for management state porduct selected in ProductoDetail, SeccionDetail and DropdownUI
export interface Selected {
  selected?: Atributo;
  setSelected?: React.Dispatch<React.SetStateAction<Atributo>>;
}

export interface ProductPropoerties extends Selected {
  cat_name: string;
  proname: string;
  attribute_price: string;
  description: string;
  atributos: Atributo[];
  imgs?: JSX.Element[];
}
