// Generated by https://quicktype.io

export interface Product {
  message: string;
  messageType: string;
  totalProducts: number;
  data: Data;
}

export interface Data {
  id: number;
  name: string;
  products_by_cat: ProductsByCat[];
}

export interface ProductsByCat {
  idp: number;
  id_o: number;
  id_category: string;
  proname: string;
  file_name?: string;
  categories?: string;
  cat_name: string;
  description: string;
  attribute_price: string;
  tax?: string;
  price?: string;
}
