// Generated by https://quicktype.io

export interface CategoriasQueryFn {
  (): Promise<Categorias>;
}

export interface Categorias {
  messageType?: string;
  message?: string;
  totalcategorias?: number;
  data?: Data;
}

export interface Data {
  current_page: number;
  data: Datum[];
  first_page_url?: string;
  from?: number;
  last_page?: number;
  last_page_url?: string;
  links?: Link[];
  next_page_url?: string;
  path?: string;
  per_page?: number;
  prev_page_url?: null;
  to?: number;
  total?: number;
}

export interface Datum {
  id: number;
  name: string;
  tree_path?: string;
  level?: number;
  status?: number;
  sx?: number;
  dx?: number;
  parent?: number;
  id_attribute_first?: number;
  id_attribute_second?: number;
  meta_keywords?: string;
  meta_description?: string;
  url_details?: string;
  icon?: string;
  position?: number;
}

export interface Link {
  url: null | string;
  label: string;
  active: boolean;
}
